// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type News struct {
	Id      int64  `json:"Id"`
	Title   string `json:"Title"`
	Content string `json:"Content"`
}

type NewsCategory struct {
	NewsId     int64 `json:"NewsId"`
	CategoryId int64 `json:"CategoryId"`
}
